import lz4 from "lz4js";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dataDirectory = path.join(project, "src", "data");
const sources = [
  ["god", "arcane-god-save.json", "full"],
  ["demigod", "arcane-demigod-save.json", "full"],
  ["missions", "arcane-voyagers-missions.json", "missions"],
];
const identityPlaceholder = Object.freeze({
  PTK: "ATLAS",
  USN: "Template",
  UID: "ATLAS_TEMPLATE",
  LID: "ATLAS_TEMPLATE",
});

function scrubIdentities(value) {
  if (Array.isArray(value)) {
    for (const item of value) scrubIdentities(item);
    return;
  }
  if (!value || typeof value !== "object") return;
  if (["PTK", "USN", "UID", "LID"].some((key) => key in value)) {
    for (const [key, replacement] of Object.entries(identityPlaceholder)) {
      if (key in value) value[key] = replacement;
    }
  }
  for (const child of Object.values(value)) scrubIdentities(child);
}

function validate(value, kind, label) {
  if (kind === "full") {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
      throw new Error(`${label} must contain a save-state object.`);
    }
    if (!value.PlayerStateData || !value.SpawnStateData) {
      throw new Error(`${label} is missing PlayerStateData or SpawnStateData.`);
    }
    return;
  }
  if (!Array.isArray(value) || !value.length) {
    throw new Error(`${label} must contain mission records.`);
  }
  const ids = value.map((record) => String(record?.Mission || ""));
  if (ids.some((id) => !id) || new Set(ids).size !== ids.length) {
    throw new Error(`${label} contains a missing or duplicate mission ID.`);
  }
}

const packed = {};
for (const [id, filename, kind] of sources) {
  const value = JSON.parse(await readFile(path.join(dataDirectory, filename), "utf8"));
  validate(value, kind, filename);
  if (kind === "full") scrubIdentities(value);
  const json = JSON.stringify(value);
  const bytes = new TextEncoder().encode(json);
  const compressed = lz4.compress(bytes);
  packed[id] = {
    kind,
    jsonBytes: bytes.length,
    base64: Buffer.from(compressed).toString("base64"),
  };
}

const output = [
  "// Generated by scripts/build_save_templates.mjs. Do not edit by hand.",
  `const packedSaveTemplates = Object.freeze(${JSON.stringify(packed)});`,
  "export default packedSaveTemplates;",
  "",
].join("\n");
const destination = path.join(dataDirectory, "save-templates-packed.js");
await writeFile(destination, output, "utf8");
console.log(`wrote ${destination} (${Buffer.byteLength(output).toLocaleString()} bytes)`);
